import type { Reservation } from './types'

function today(): string {
  return new Date().toISOString().split('T')[0]
}

function tomorrow(): string {
  const d = new Date()
  d.setDate(d.getDate() + 1)
  return d.toISOString().split('T')[0]
}

function daysFromNow(n: number): string {
  const d = new Date()
  d.setDate(d.getDate() + n)
  return d.toISOString().split('T')[0]
}

export const mockReservations: Reservation[] = [
  // Bugünkü rezervasyonlar
  {
    id: '1',
    reservationNo: 'UNC-20260319-001',
    customerName: 'Ahmet Yılmaz',
    customerEmail: 'ahmet@gmail.com',
    customerPhone: '+90 532 111 2233',
    city: 'Antalya',
    hotel: 'Rixos Premium Belek',
    checkIn: today(),
    checkOut: daysFromNow(5),
    guests: 2,
    roomType: 'Deluxe Suite',
    status: 'confirmed',
    totalPrice: 42500,
    currency: 'TRY',
    notes: 'Deniz manzaralı oda tercih edildi.',
    createdAt: '2026-03-15T10:30:00Z',
  },
  {
    id: '2',
    reservationNo: 'UNC-20260319-002',
    customerName: 'Fatma Demir',
    customerEmail: 'fatma.demir@hotmail.com',
    customerPhone: '+90 555 444 5566',
    city: 'Antalya',
    hotel: 'Calista Luxury Resort',
    checkIn: today(),
    checkOut: daysFromNow(7),
    guests: 4,
    roomType: 'Family Room',
    status: 'confirmed',
    totalPrice: 68000,
    currency: 'TRY',
    createdAt: '2026-03-14T14:20:00Z',
  },
  {
    id: '3',
    reservationNo: 'UNC-20260319-003',
    customerName: 'Mehmet Kaya',
    customerEmail: 'mkaya@yahoo.com',
    customerPhone: '+90 541 777 8899',
    city: 'İstanbul',
    hotel: 'Four Seasons Bosphorus',
    checkIn: today(),
    checkOut: daysFromNow(3),
    guests: 2,
    roomType: 'Bosphorus View Room',
    status: 'pending',
    totalPrice: 35000,
    currency: 'TRY',
    notes: 'VIP transfer talep edildi.',
    createdAt: '2026-03-16T09:15:00Z',
  },
  {
    id: '4',
    reservationNo: 'UNC-20260319-004',
    customerName: 'Ayşe Çelik',
    customerEmail: 'ayse.celik@gmail.com',
    customerPhone: '+90 505 333 4455',
    city: 'Bodrum',
    hotel: 'Mandarin Oriental Bodrum',
    checkIn: today(),
    checkOut: daysFromNow(4),
    guests: 2,
    roomType: 'Sea View Suite',
    status: 'confirmed',
    totalPrice: 55000,
    currency: 'TRY',
    createdAt: '2026-03-17T16:45:00Z',
  },

  // Yarınki rezervasyonlar
  {
    id: '5',
    reservationNo: 'UNC-20260320-001',
    customerName: 'Ali Öztürk',
    customerEmail: 'ali.ozturk@gmail.com',
    customerPhone: '+90 533 222 1100',
    city: 'Antalya',
    hotel: 'Regnum Carya',
    checkIn: tomorrow(),
    checkOut: daysFromNow(8),
    guests: 3,
    roomType: 'King Suite',
    status: 'confirmed',
    totalPrice: 78000,
    currency: 'TRY',
    notes: 'Golf sahası yakını oda istendi.',
    createdAt: '2026-03-18T11:00:00Z',
  },
  {
    id: '6',
    reservationNo: 'UNC-20260320-002',
    customerName: 'Zeynep Arslan',
    customerEmail: 'zeynep@outlook.com',
    customerPhone: '+90 544 666 7788',
    city: 'İstanbul',
    hotel: 'Çırağan Palace Kempinski',
    checkIn: tomorrow(),
    checkOut: daysFromNow(4),
    guests: 2,
    roomType: 'Palace Suite',
    status: 'confirmed',
    totalPrice: 92000,
    currency: 'TRY',
    createdAt: '2026-03-18T13:30:00Z',
  },
  {
    id: '7',
    reservationNo: 'UNC-20260320-003',
    customerName: 'Can Yıldırım',
    customerEmail: 'can.yildirim@gmail.com',
    customerPhone: '+90 507 999 0011',
    city: 'Kapadokya',
    hotel: 'Museum Hotel',
    checkIn: tomorrow(),
    checkOut: daysFromNow(3),
    guests: 2,
    roomType: 'Cave Suite',
    status: 'pending',
    totalPrice: 28000,
    currency: 'TRY',
    notes: 'Balon turu dahil paket.',
    createdAt: '2026-03-18T15:00:00Z',
  },

  // Diğer günler
  {
    id: '8',
    reservationNo: 'UNC-20260321-001',
    customerName: 'Elif Şahin',
    customerEmail: 'elif.sahin@gmail.com',
    customerPhone: '+90 538 111 2200',
    city: 'Bodrum',
    hotel: 'The Bodrum EDITION',
    checkIn: daysFromNow(2),
    checkOut: daysFromNow(6),
    guests: 2,
    roomType: 'Marina Suite',
    status: 'confirmed',
    totalPrice: 47500,
    currency: 'TRY',
    createdAt: '2026-03-17T10:00:00Z',
  },
  {
    id: '9',
    reservationNo: 'UNC-20260321-002',
    customerName: 'Burak Koç',
    customerEmail: 'burak.koc@gmail.com',
    customerPhone: '+90 542 555 6677',
    city: 'Antalya',
    hotel: 'Maxx Royal Belek',
    checkIn: daysFromNow(2),
    checkOut: daysFromNow(9),
    guests: 5,
    roomType: 'Royal Villa',
    status: 'confirmed',
    totalPrice: 125000,
    currency: 'TRY',
    notes: 'Özel havuzlu villa.',
    createdAt: '2026-03-16T08:30:00Z',
  },
  {
    id: '10',
    reservationNo: 'UNC-20260322-001',
    customerName: 'Selin Aydın',
    customerEmail: 'selin@gmail.com',
    customerPhone: '+90 531 444 5500',
    city: 'Kapadokya',
    hotel: 'Argos in Cappadocia',
    checkIn: daysFromNow(3),
    checkOut: daysFromNow(6),
    guests: 2,
    roomType: 'Splendid Suite',
    status: 'confirmed',
    totalPrice: 32000,
    currency: 'TRY',
    createdAt: '2026-03-15T12:00:00Z',
  },
  {
    id: '11',
    reservationNo: 'UNC-20260322-002',
    customerName: 'Emre Güneş',
    customerEmail: 'emre.gunes@gmail.com',
    customerPhone: '+90 536 888 9900',
    city: 'İstanbul',
    hotel: 'Raffles Istanbul',
    checkIn: daysFromNow(3),
    checkOut: daysFromNow(5),
    guests: 1,
    roomType: 'Deluxe Room',
    status: 'cancelled',
    totalPrice: 18500,
    currency: 'TRY',
    notes: 'İptal edildi — müşteri talebi.',
    createdAt: '2026-03-14T09:00:00Z',
  },
  {
    id: '12',
    reservationNo: 'UNC-20260325-001',
    customerName: 'Deniz Yalçın',
    customerEmail: 'deniz@gmail.com',
    customerPhone: '+90 539 222 3344',
    city: 'Antalya',
    hotel: 'Titanic Mardan Palace',
    checkIn: daysFromNow(6),
    checkOut: daysFromNow(13),
    guests: 3,
    roomType: 'Grand Suite',
    status: 'pending',
    totalPrice: 95000,
    currency: 'TRY',
    createdAt: '2026-03-18T17:00:00Z',
  },
]
